// Generated by gencpp from file utils/GetTransform.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GETTRANSFORM_H
#define UTILS_MESSAGE_GETTRANSFORM_H

#include <ros/service_traits.h>


#include <utils/GetTransformRequest.h>
#include <utils/GetTransformResponse.h>


namespace utils
{

struct GetTransform
{

typedef GetTransformRequest Request;
typedef GetTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTransform
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::GetTransform > {
  static const char* value()
  {
    return "4c5026dc3bd8461725969574664a41aa";
  }

  static const char* value(const ::utils::GetTransform&) { return value(); }
};

template<>
struct DataType< ::utils::GetTransform > {
  static const char* value()
  {
    return "utils/GetTransform";
  }

  static const char* value(const ::utils::GetTransform&) { return value(); }
};


// service_traits::MD5Sum< ::utils::GetTransformRequest> should match
// service_traits::MD5Sum< ::utils::GetTransform >
template<>
struct MD5Sum< ::utils::GetTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::GetTransform >::value();
  }
  static const char* value(const ::utils::GetTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::GetTransformRequest> should match
// service_traits::DataType< ::utils::GetTransform >
template<>
struct DataType< ::utils::GetTransformRequest>
{
  static const char* value()
  {
    return DataType< ::utils::GetTransform >::value();
  }
  static const char* value(const ::utils::GetTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::GetTransformResponse> should match
// service_traits::MD5Sum< ::utils::GetTransform >
template<>
struct MD5Sum< ::utils::GetTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::GetTransform >::value();
  }
  static const char* value(const ::utils::GetTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::GetTransformResponse> should match
// service_traits::DataType< ::utils::GetTransform >
template<>
struct DataType< ::utils::GetTransformResponse>
{
  static const char* value()
  {
    return DataType< ::utils::GetTransform >::value();
  }
  static const char* value(const ::utils::GetTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_GETTRANSFORM_H
