// Generated by gencpp from file utils/GetTransformRequest.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GETTRANSFORMREQUEST_H
#define UTILS_MESSAGE_GETTRANSFORMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct GetTransformRequest_
{
  typedef GetTransformRequest_<ContainerAllocator> Type;

  GetTransformRequest_()
    : target_frame()
    , source_frame()  {
    }
  GetTransformRequest_(const ContainerAllocator& _alloc)
    : target_frame(_alloc)
    , source_frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_frame_type;
  _target_frame_type target_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_frame_type;
  _source_frame_type source_frame;





  typedef boost::shared_ptr< ::utils::GetTransformRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::GetTransformRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTransformRequest_

typedef ::utils::GetTransformRequest_<std::allocator<void> > GetTransformRequest;

typedef boost::shared_ptr< ::utils::GetTransformRequest > GetTransformRequestPtr;
typedef boost::shared_ptr< ::utils::GetTransformRequest const> GetTransformRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::GetTransformRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::GetTransformRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::GetTransformRequest_<ContainerAllocator1> & lhs, const ::utils::GetTransformRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_frame == rhs.target_frame &&
    lhs.source_frame == rhs.source_frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::GetTransformRequest_<ContainerAllocator1> & lhs, const ::utils::GetTransformRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::GetTransformRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::GetTransformRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::GetTransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::GetTransformRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::GetTransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::GetTransformRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::GetTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cca159d7671f770d19e4e288854c223";
  }

  static const char* value(const ::utils::GetTransformRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cca159d7671f770ULL;
  static const uint64_t static_value2 = 0xd19e4e288854c223ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::GetTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/GetTransformRequest";
  }

  static const char* value(const ::utils::GetTransformRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::GetTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string target_frame\n"
"string source_frame\n"
;
  }

  static const char* value(const ::utils::GetTransformRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::GetTransformRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_frame);
      stream.next(m.source_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTransformRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::GetTransformRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::GetTransformRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_frame);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_GETTRANSFORMREQUEST_H
