// Generated by gencpp from file abb_control/ArmGoal.msg
// DO NOT EDIT!


#ifndef ABB_CONTROL_MESSAGE_ARMGOAL_H
#define ABB_CONTROL_MESSAGE_ARMGOAL_H

#include <ros/service_traits.h>


#include <abb_control/ArmGoalRequest.h>
#include <abb_control/ArmGoalResponse.h>


namespace abb_control
{

struct ArmGoal
{

typedef ArmGoalRequest Request;
typedef ArmGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmGoal
} // namespace abb_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_control::ArmGoal > {
  static const char* value()
  {
    return "5d29b6219247a57177fcffb880bc2f7e";
  }

  static const char* value(const ::abb_control::ArmGoal&) { return value(); }
};

template<>
struct DataType< ::abb_control::ArmGoal > {
  static const char* value()
  {
    return "abb_control/ArmGoal";
  }

  static const char* value(const ::abb_control::ArmGoal&) { return value(); }
};


// service_traits::MD5Sum< ::abb_control::ArmGoalRequest> should match
// service_traits::MD5Sum< ::abb_control::ArmGoal >
template<>
struct MD5Sum< ::abb_control::ArmGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_control::ArmGoal >::value();
  }
  static const char* value(const ::abb_control::ArmGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_control::ArmGoalRequest> should match
// service_traits::DataType< ::abb_control::ArmGoal >
template<>
struct DataType< ::abb_control::ArmGoalRequest>
{
  static const char* value()
  {
    return DataType< ::abb_control::ArmGoal >::value();
  }
  static const char* value(const ::abb_control::ArmGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_control::ArmGoalResponse> should match
// service_traits::MD5Sum< ::abb_control::ArmGoal >
template<>
struct MD5Sum< ::abb_control::ArmGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_control::ArmGoal >::value();
  }
  static const char* value(const ::abb_control::ArmGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_control::ArmGoalResponse> should match
// service_traits::DataType< ::abb_control::ArmGoal >
template<>
struct DataType< ::abb_control::ArmGoalResponse>
{
  static const char* value()
  {
    return DataType< ::abb_control::ArmGoal >::value();
  }
  static const char* value(const ::abb_control::ArmGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_CONTROL_MESSAGE_ARMGOAL_H
